### ISSUE TITLE
Too many files crashes

### ISSUE THREAD

**Issue by licaon-kter** [M66B/NetGuard#307] opened 2016-02-10 11:39 UTC
Xperia 5.1.1, 0.86-beta2
Logcat: https://gist.github.com/licaon-kter/3d7d2d4e9135188b6e46

**Comment by M66B** [comment] 2016-02-10 11:58
What exactly were you doing on the device?
How many sessions are shown in the network speed notification?

**Comment by licaon-kter** [comment] 2016-02-10 12:05
Was with screen lock for a while, opened to see a chat app was disconnected, and NetGuard went poof.
No idea on sessions, I have that off usually.

I'll turn it on just in case.

**Comment by M66B** [comment] 2016-02-10 12:07
Which chat app are you using? Skype?

**Comment by licaon-kter** [comment] 2016-02-10 12:09
https://github.com/siacs/Conversations

Looks like all the uninstalling got NetGuard off the battery exception list, I added it back now, not sure if that was at fault though.

**Comment by M66B** [comment] 2016-02-10 19:37
Can you executed this command in a terminal:

```
cat /proc/sys/fs/file-nr
```

For reference my values: 
```
6602	0	**157028**
```

More information:
https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/5/html/Tuning_and_Optimizing_Red_Hat_Enterprise_Linux_for_Oracle_9i_and_10g_Databases/chap-Oracle_9i_and_10g_Tuning_Guide-Setting_File_Handles.html

**Comment by M66B** [comment] 2016-02-10 19:52
Test version, which shows the percentage of maximum number of files used the upper right corner:
http://www.netguard.me/NetGuard-v0.86-beta-2016020902-all-release-2.apk
(and of course all other work of today)

Also the logcat will include a list of open files, but writing a logcat will not work when the maximum number of files has been reached.

**Comment by M66B** [comment] 2016-02-10 20:20
Somebody reported:
```
7617 0 157028
```

So, a maximum number of files open of 157028 seems to be common.

**Comment by licaon-kter** [comment] 2016-02-10 20:58
```
$ cat /proc/sys/fs/file-nr
5942    0       243953
```

**Comment by M66B** [comment] 2016-02-10 21:00
Your maximum is higher than mine.

Try reproducing the issue and see what happens with the first number (number of open files).

**Comment by licaon-kter** [comment] 2016-02-10 21:03
I did not see this issue again today after I put NetGuard back on the [Stamina Mode whitelist](http://developer.sonymobile.com/2013/04/03/how-sonys-battery-stamina-mode-works/) so that might be a factor.

Although, NetGuard should cope with it. I'll have a look at the logcat since then and asses the situation.

**Comment by actinium227** [comment] 2016-02-11 05:27
netguard had crashed a few hours ago, just ran it on terminal

`8155 0 157028`

hard to notice the crash unless i am actively doing something on the phone

**Comment by M66B** [comment] 2016-02-11 06:30
After the crash the file count will be back to normal.

Please check also the logcat to make sure it is the same problem.

**Comment by M66B** [comment] 2016-02-11 13:11
This issue should be fixed in the upcoming version, but please feel free to reopen when this is not the case.

**Closed by M66B** 2016-02-11 13:11 UTC
Labels: bug
