### ISSUE TITLE
VZW MMS broken when connected to WiFi

### ISSUE THREAD

**Issue by doctorray117** [M66B/NetGuard#398] opened 2016-03-31 18:03 UTC
NetGuard v2.15
Samsung Galaxy S7 Edge on Verizon Wireless.

Using NetGuard, while connected to WiFi, I am unable to send MMS messages.  Receiving them is intermittent, sometimes it works but mostly it does not (though maybe that was a fluke when I walked outside of wifi range).  I took a packet capture from an upstream router while attempting to send a picture message while on WiFi, and it appears that the phone is attempting to perform a DNS lookup on mms.vtext.com.  My DNS server fails to look up this value, hence the message is stuck and fails.

Would it be possible to detect and route this DNS request through the mobile data network, as well as any further traffic resulting from that IP's resolution?

I'm using textra as a client and attempted to block its access to WiFi but that did not seem to help.  I am unsure if I would be able to get a good packet capture of MMS traffic on mobile data unless NetGuard can do this.  Worst case scenario I can get out my rooted S4 and try and get a packet capture on that at a later time.

Thank you.

**Comment by licaon-kter** [comment] 2016-03-31 19:11
Usually TelCo's only send/receive MMS using the mobile network, rarely they accept it through Wi-Fi, if you just allow the SMS app for mobile does it work?

**Comment by doctorray117** [comment] 2016-03-31 19:22
@licaon-kter tried that to no avail.

I bought the traffic logging pro feature and took a pcap of a mms message.  It did a DNS lookup for mms.vtext.com but ended up shoving the traffic at mms3.vtext.com.  From adb shell I could see by pinging that mms1 through mms6 exist and are publicly resolvable.  Trying to telnet into port 80 from my desk on those IPs results in a hung connection, as if they are firewalled to only accept traffic from the mobile network (which makes sense).

The DNS request must come from somewhere deeper in the android subsystem, which is why it failed.  I could try experimenting by adding those 7 records (mms, mms1...mms6) to the hosts file with their real IPs, disabling traffic for the app on WiFi and trying again.  Otherwise I feel that static routes will be necessary?

**Comment by M66B** [comment] 2016-03-31 20:09
I don't think this problem is caused by NetGuard.

NetGuard is a firewall and not meant for routing (which would also takes its toll on the battery).

I don't see what can be done from the perspective of NetGuard, so I am going to close this issue, but feel free to report your findings and ask follow up questions here.

**Closed by M66B** 2016-03-31 20:09 UTC

**Comment by doctorray117** [comment] 2016-03-31 20:25
Thanks, I totally understand.  I thought that there was something NetGuard may have been overriding that forced all the traffic out the default route, be it wifi or mobile data.

Diving further into the APN settings and Textra settings, I found that I could switch Textra from "legacy" to "system" in the MMS settings, and lo and behold, it works now with NetGuard enabled.  Sorry for the trouble and thank you for the bandwidth.
