### ISSUE TITLE
Allow installation on Android TV devices through Play Store

### ISSUE THREAD

**Issue by fhemberger** [M66B/NetGuard#302] opened 2016-02-09 08:44 UTC
I own a Sony Bravia running Android, but I can't install NetGuard through Google's Play Store (application not compatible with device). As such "Smart TVs" are probably the worst offenders when it comes to privacy, it would be great if NetGuard could be installed there as well.

I don't know what has to be changed in the code to get this running, but I'm happy to help testing (device is already in development mode and I can connect via `adb` to it).

**Comment by M66B** [comment] 2016-02-09 08:46
You can try to install the latest beta version.

Before allowing NetGuard to install on Android TV via the Play store, this issue needs to be resolved:
http://forum.xda-developers.com/showpost.php?p=65222104&postcount=1271

**Comment by fhemberger** [comment] 2016-02-17 11:17
Just tried NetGuard-v0.89-beta-2016021601, after sending the TV to standby, the device reboots once I wake it up again (no hanging, just a clean reboot). Hope you can squish this bug soon!

**Comment by M66B** [comment] 2016-02-21 15:54
Unless somebody sends me an Android TV or fixes this problem, I don't see this issue resolved.

**Comment by fhemberger** [comment] 2016-02-22 05:28
Sorry, I can't send you a TV but I'm ready to help testing this further.

**Comment by M66B** [comment] 2016-02-22 07:21
Try installing the latest beta version with managing system applications disabled.

**Comment by licaon-kter** [comment] 2016-02-22 21:12
Android emulator is running on your e machine? (albeit slow) They do have an AndroidTV instance there...

**Comment by M66B** [comment] 2016-02-22 21:14
I don't have the hardware to run the emulator.

**Comment by fhemberger** [comment] 2016-02-25 15:46
Just tried v0.95 with systems applications disabled, unfortunately the same behavior.
Switched TV to standby, woke it up after two seconds, LED flashes green/red/yellow/blue a few times, then blinks red a few times, reboots TV.

Is there some sort of crash log on Android, which I can attach to this issue for easier debugging? Already poked around a bit with adb shell, but – of course – my TV isn't rooted, so I can't access many directories there.

**Comment by M66B** [comment] 2016-02-25 15:52
The best you can do is capturing a logcat via adb and reproduce the issue.
Normally the crash will be in the logcat this way.
For hard crashes there is another way, but I don't think this will be necessary in this case.

**Comment by stiggy2k16** [comment] 2016-03-23 13:51
FWIW, NetGuard works perfectly on my Nexus Player. Been using it for a number of days now quite happily.

The only (very minor) issue I've found is that the "Disable Battery Optimization" popup shows when it doesn't need to, and clicking "OK" rather than "Cancel" to the popup will crash NetGuard.

**Comment by licaon-kter** [comment] 2016-03-23 16:54
After a crash do start NetGuard->About and tap that dialogue 7 times, the resulting logcat paste it here on https://gist.github.com

**Comment by M66B** [comment] 2016-04-01 06:02
@stiggy2k16 your issue should be fixed in the latest version
@fhemberger could you please try the latest version and enabling the new option '*Allow LAN access*' ?

**Comment by M66B** [comment] 2016-04-01 06:02
http://developer.android.com/training/tv/start/start.html

**Comment by fhemberger** [comment] 2016-04-01 08:25
Tried latest 2.16b release:

- Activated NetGuard (no blocking), send TV to sleep with remote, wait 10 seconds, activate TV again with remote. LED flashes red-yellow-green-blue, then flashes red six times (repeatedly), press remote again, TV reboots. [logcat dump](https://gist.github.com/fhemberger/b9b848652ed68083c42a96ec8dfbe114#file-netguard-no-blocking-log)

- Same with blocking enabled: TV doesn't react to remote control any more after sent to sleep, requires hard reset. [logcat dump](https://gist.github.com/fhemberger/b9b848652ed68083c42a96ec8dfbe114#file-netguard-blocking-log)

**Comment by fhemberger** [comment] 2016-04-27 08:34
@M66B Were the logs of any help?

**Comment by M66B** [comment] 2016-04-27 08:47
No, there was nothing which could explain the problem.

**Comment by fhemberger** [comment] 2016-04-27 08:51
#sadpanda

**Comment by M66B** [comment] 2016-07-03 09:33
Since nobody else asked for this feature, my conclusion the interest for this is too limited to put effort into.

**Closed by M66B** 2016-07-03 09:33 UTC
Labels: enhancement, lowprio
