### ISSUE TITLE
Compilation Issue

### ISSUE THREAD

**Issue by GermMuz** [M66B/NetGuard#258] opened 2016-01-29 20:40 UTC
When trying to compile using the latest android studio 1.5.1 with all updates I get the error:

See file:///C:/Users/Glenn/Documents/Android/NetGuard-0.77-7/app/build/tmp/compileArm64-v8aDebugNetguardSharedLibraryNetguardMainC/output.txt for all output for compileArm64-v8aDebugNetguardSharedLibraryNetguardMainC.
compiling netguard.c failed.

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
Assertion failed!

Program: C:\Users\Glenn\AppData\Local\Android\Sdk\ndk-bundle\toolchains\llvm-3.6\prebuilt\windows-x86_64\bin\clang.exe
File: /s/ndk-toolchain/src/llvm-3.6/llvm/lib/Option/OptTable.cpp, Line 285

Expression: Index >= End && "Unexpected parser error."

Finished compileArm64-v8aDebugNetguardSharedLibraryNetguardMainC, see full log file:///C:/Users/Glenn/Documents/Android/NetGuard-0.77-7/app/build/tmp/compileArm64-v8aDebugNetguardSharedLibraryNetguardMainC/output.txt.

 I have tried a few versions of the code and get the same problem. I am using windows 10 64 bit. This might be a google bug as googling it others have had it.

Any ideas????

Thx

**Comment by M66B** [comment] 2016-01-29 20:41
Duplicate of two similar issues.

**Closed by M66B** 2016-01-29 20:41 UTC
