### ISSUE TITLE
pselect error 9: Bad file numer

### ISSUE THREAD

**Issue by Thyra-Sinisalo** [M66B/NetGuard#431] opened 2016-05-21 06:44 UTC
Hi, after using NetGuard for a few hours, I got the notification 
"NetGuard has been disabled, because of an internal error
pselect error 9: Bad file number"
I went to NetGuard, re-enabled it with the switch, it got promptly disabled again. Tried several more times, same result. Tried reinstalling. This time the same thing happened but I was able to re-enable it after several tries.
I'll keep you posted on future development.

**Comment by licaon-kter** [comment] 2016-05-21 07:36
/duplicate of #420 

Device? Android version? Any proxy/routers/syncthing running?

**Comment by Thyra-Sinisalo** [comment] 2016-05-21 09:27
Sorry, should have thought of that.
Device: Huawei Ascend G620S-L01
Android 4.4.4
As for the last question, the best I can give you is None that I know of, based on what I googled. I only have a rough idea what you are talking about. I know I have never used Syncthing (or even heard about it before).

**Comment by M66B** [comment] 2016-05-21 11:48
Please provide a logcat

Thyra-Sinisalo <notifications@github.com> schreef op 21 mei 2016 04:27:44 GMT-05:00:

**Comment by licaon-kter** [comment] 2016-05-22 07:37
@Thyra-Sinisalo That's NetGuard->menu->About->tap dialogue 7 times->save the file-> paste it at https://gist.github.com ->paste link here

**Comment by Thyra-Sinisalo** [comment] 2016-05-23 08:16
I installed aLogcat 2 days ago and when it happened yesterday, I saved the file but all there was is this: [https://gist.github.com/Thyra-Sinisalo/f941766d735e0bb14896ff9ba66906e5](url)
Does it contain anything useful or does my phone have to be rooted (it is not)?

@licaon-kter I only read you message now (thank you for the tip!) and when I tried it, it seemed to mage a log that goes back about 3 minutes so I suppose I will need to wait until it happens again (and actually catch it on time), right?

**Comment by licaon-kter** [comment] 2016-05-23 08:41
Yes, when you see it go straight to the About screen.

BTW, you did not link correctly.

**Comment by Thyra-Sinisalo** [comment] 2016-05-23 08:52
Sorry, I'm not sure what went wrong. I used the "Share" option to get a link, then the "Add a link" option here. However, it works if I just copy and paste the link above.
Another (blind) try with Embed: <script src="https://gist.github.com/Thyra-Sinisalo/f941766d735e0bb14896ff9ba66906e5.js"></script>

**Comment by licaon-kter** [comment] 2016-05-23 08:58
You need to either format it as `[title](actual link)` or just paste the link

**Comment by Thyra-Sinisalo** [comment] 2016-05-23 09:00
https://gist.github.com/Thyra-Sinisalo/f941766d735e0bb14896ff9ba66906e5

**Comment by licaon-kter** [comment] 2016-05-23 09:14
Link is ok now, the log is not useful though.

**Comment by LaGlobule** [comment] 2016-05-28 22:17
Hi MB66
I've got the same message and the same behaviour regarding the impossibility to restart NetGuard.
So I had to reboot.
Here attached the logcat.
This problem occurs since a few versions but I don't remember when I first got it.
Thanks.
[logcat.txt](https://github.com/M66B/NetGuard/files/288038/logcat.txt)

**Comment by Thyra-Sinisalo** [comment] 2016-05-29 11:33
It has not happened to me for a week. I have no idea why, what or if anything changed. Before it took just a few hours of use.

**Comment by M66B** [comment] 2016-06-07 12:56
@licaon-kter: could you please try if reducing either SELECT_TIMEOUT or TCP_IDLE_TIMEOUT fixes this problem?

I would try a select timeout of 120 or 180 seconds and a TCP idle timeout of 300 or 600 seconds.

These constants are declared in the source file netguard.h

If you like you can create a pull request to update the gradle plugin to the latest version.

I will be traveling two weeks more, see http://blog.bokhorst.eu/

**Comment by licaon-kter** [comment] 2016-06-07 17:01
Done, I'll report back.

**Comment by Thyra-Sinisalo** [comment] 2016-06-08 06:34
Happened twice more, here are the logcats. I think the first one caught it at least: 
1) https://gist.github.com/anonymous/94303a6d720f1e0df01a35079defc1bb
2) https://gist.github.com/Thyra-Sinisalo/e84e25e133efad3af6fdbdd553948605

**Comment by licaon-kter** [comment] 2016-06-08 06:48
Reduced SELECT_TIMEOUT to 120 and TCP_IDLE_TIMEOUT to 300 and still got it ( `pselect error 9: Bad file descriptor` ), but it was even worse, while I usually see it after some screen off rest/standby period, say during the night or exiting Wi-Fi connection area with the screen off, now I got it while standing still in the area of that said Wi-Fi while I was browsing the internet (screen on of course).

Logcat incoming.

**Comment by licaon-kter** [comment] 2016-06-08 08:14
And logcat with comments: https://gist.github.com/licaon-kter/9078c710cf758c4f70fcf444ba4d73c2

**Comment by M66B** [comment] 2016-06-08 08:17
Too bad that changing the timeouts does not help and even seems to worsen things :-(

**Comment by M66B** [comment] 2016-06-08 23:21
I see the following solutions:

* find a more compatible way to check the validity of file descriptor (sockets)
* reset all connections on pselect error
* switch to epoll

Besides being a lot of work, the latter might introduce new incompatibilities. In general pselect is better supported by kernel, though slightly less efficient.

The first solution is preferable, but I don't know if there is a better/alternate way of checking file descriptors as currently is being used.

**Comment by M66B** [comment] 2016-06-08 23:26
http://stackoverflow.com/questions/12340695/how-to-check-if-a-given-file-descriptor-stored-in-a-variable-is-still-valid

**Comment by M66B** [comment] 2016-06-23 15:01
For now I have changed the way how file descriptors are being checked.

Test version: http://www.netguard.me/NetGuard-v2.25-2016062301-sdk-23-all-release.apk

Please let me know if this improves things.

**Comment by licaon-kter** [comment] 2016-06-23 21:20
Ok, I'll test.

**Comment by licaon-kter** [comment] 2016-06-24 20:23
Oh you're back alright, :)
So many changes, I'll start compiling right away.

/on that note, the last crash was a week ago, now it's working fine when you're back and epoll is here :) :)

**Comment by M66B** [comment] 2016-06-24 20:29
Yes, I am back ,:-)
epoll was a lot of work, but it seems to work okay.
It will use less battery as well and be faster.
Testing is very welcome.
I like to know if this issue has been solved.

**Comment by M66B** [comment] 2016-06-30 05:33
So, do the recent versions solve this problem?

**Comment by licaon-kter** [comment] 2016-06-30 05:39
I did not get any so far, I'll update another device today, but looks good so far. :+1:

**Comment by M66B** [comment] 2016-06-30 08:23
With more than 8500 downloads and not a single complaint, I am going to assume this issue has been fixed and that the rewrite didn't had side effects.

**Closed by M66B** 2016-06-30 08:23 UTC
Labels: bug

**Comment by licaon-kter** [comment] 2016-06-30 09:39
Spoke too soon, it's back, hopefully the logs help now. :(

Was on mobile, entered Wi-Fi range, open screen, poof: https://gist.github.com/licaon-kter/967bf5c9cfdc1c54169670766fec4135

Custom build up to c8fcf87

**Comment by M66B** [comment] 2016-06-30 09:43
'FAILED BINDER TRANSACTION' is not the same issue as pselect error 9.
I don't see error 9 (EBADF) anywhere in the log.

'FAILED BINDER TRANSACTION' is being caused by the Android VPN service dying (which is part of Android not NetGuard). NetGuard is requesting the VPN service to start by Android and the component responsible for doing this has died (crashed?). There is nothing that can be done from NetGuard to fix this.

**Comment by licaon-kter** [comment] 2016-06-30 10:13
#420 and #291 have these linked, as you can see.

**Comment by M66B** [comment] 2016-06-30 10:48
I the beginning I though the issues were linked, but they appear not to be linked.

As explained before I cannot solve binder transaction problems, whatever the cause is.

**Comment by M66B** [comment] 2016-07-06 06:30
Issue locked because pselect is not being used anymore.
