### ISSUE TITLE
Theme names end up as UDP/TCP

### ISSUE THREAD

**Issue by licaon-kter** [M66B/NetGuard#305] opened 2016-02-09 21:11 UTC
Since https://github.com/M66B/NetGuard/commit/5c13c4ab0ce1f494e5854a3cfe82f0f72fcfd710 the theme names end up as UDP and TCP and they work as the first and second theme.
But all the other themes, while they do apply, make the main text `setting_theme` dissappear, also the theme description never appears.

**Comment by M66B** [comment] 2016-02-09 21:14
Maybe I don't understand what you mean, but for me the theme names appear correctly.

If you did build yourself, clean the project once.

**Comment by licaon-kter** [comment] 2016-02-09 21:16
Nope, downloaded your build, even clean data once.

I'll get pics.

**Comment by licaon-kter** [comment] 2016-02-09 21:20
Default theme: https://i.imgur.com/LPfZvD5.jpg
(second theme is TCP, hunce my idea that the string-arry is read wrong or something)
Third theme: https://i.imgur.com/23PDM5N.jpg

**Comment by licaon-kter** [comment] 2016-02-10 07:30
That's Xperia 5.1.1 but I see the same on Samsung 5.0.2 and CM13, so it's not a ROM thing.

**Comment by M66B** [comment] 2016-02-10 08:13
My best guess is that this is caused by a build problem.

Can you please switch your device(s) to English and check if the same problem is there?

**Comment by M66B** [comment] 2016-02-10 08:15
The source code (from Crowdin) is okay:
https://github.com/M66B/NetGuard/blob/master/app/src/main/res/values-ro/strings.xml#L163

English original code:
https://github.com/M66B/NetGuard/blob/master/app/src/main/res/values/strings.xml#L189

**Comment by licaon-kter** [comment] 2016-02-10 08:50
I've already tested with English (UK IIRC) but looks like I forgot to mention it.

**Comment by M66B** [comment] 2016-02-10 08:53
So, English has the same problem?

**Comment by licaon-kter** [comment] 2016-02-10 08:58
Switched to French, uninstalled, reinstalled, excepted in XPrivacy... same issue.

**Comment by M66B** [comment] 2016-02-10 09:00
This will likely be fixed in the next build, for which I will run a clean project first.
Android Studio has its quirks ...

**Closed by M66B** 2016-02-10 09:00 UTC

**Comment by licaon-kter** [comment] 2016-02-10 14:05
Fixed by the other issue build. 10x
