### ISSUE TITLE
Control over individual apps

### ISSUE THREAD

**Issue by malitech** [M66B/NetGuard#317] opened 2016-02-13 20:32 UTC
Enabling internet access to Download manager is also giving permission to downloads ui and media storage to which I never gave internet access before in any firewall. Even if related apps enable themselves, I should still have control to disable them individually. There's no way to use download manager without providing access to media storage and downloads ui. Right now I've found a workaround to enable only download manager and disable the other two. Pleaseeee fix this.

**Comment by licaon-kter** [comment] 2016-02-13 20:43
What exactly are `downloads ui` and `media storage` doing wrong exactly?

They probably share the same UID (blame your ROM I guess).

/duplicate of https://github.com/M66B/NetGuard/issues/309

**Comment by M66B** [comment] 2016-02-13 20:46
Do the applications have the same uid?
If so, then they can't be controlled apart and there is nothing which can be done to change that.
How did you work around this?

**Comment by malitech** [comment] 2016-02-13 21:00
In the previous versions, NetGuard would allow me to disable apps individually. I had only seen play store giving access to services...etc. This one is new. 

![screenshot_20160214-022205 01](https://cloud.githubusercontent.com/assets/7058205/13030012/57e07f08-d2c2-11e5-8a77-de2d9a186da4.png)

**Comment by M66B** [comment] 2016-02-13 21:02
Yes, it is new to reflect the actual situation.

**Comment by malitech** [comment] 2016-02-13 21:02
The workaround is enabling chrome browser enables only download manager. So, that way I can achieve what's seen in the screenshot above. 
Hope there is a solution. I don't want the other two contacting any server.

**Comment by malitech** [comment] 2016-02-13 21:03
Oh man, wait until I type. :D

**Closed by M66B** 2016-02-13 21:02 UTC
Labels: question

**Comment by M66B** [comment] 2016-02-13 21:05
I am sorry, but this can and will not be fixed. Blocking one will block the others, even though the settings may not reflect this. I will fix your 'workaround' too.

**Comment by malitech** [comment] 2016-02-13 21:10
But it could be done before. Why this merging?
Oh no. I tested and the download manager works well with the other two blocked.

**Comment by licaon-kter** [comment] 2016-02-13 21:18
> I tested and the download manager works well with the other two blocked.

How did you _test_ that the *other two* were blocked?
