### ISSUE TITLE
PCAP file format issue

### ISSUE THREAD

**Issue by GermMuz** [M66B/NetGuard#259] opened 2016-01-30 08:14 UTC
Using 0.79 compiled on a mac. (latest Android Studio NDK on windows seems bugged)

I have captured some pcap files but they fail to load in Wireshark 2.0.1, Wireshark says it isn't in a format that it understands.

**Comment by M66B** [comment] 2016-01-30 08:19
Works fine for me in Wireshark 1.10.6 (Linux).

The PCAP file version is 2.4 as documented here:
https://wiki.wireshark.org/Development/LibpcapFileFormat

Which Wireshark version are you using?

**Comment by M66B** [comment] 2016-01-30 08:21
Maybe the file got modified/corrupted while transferring it to your Mac.

**Comment by GermMuz** [comment] 2016-01-30 12:24
I transferred the file via google drive over to a PC to run Wireshark. I'll try is again and pull the file apart in my own program. It could have got corrupted.

**Comment by M66B** [comment] 2016-01-30 12:27
I am using 

```
adb pull /sdcard/Download/netguard_yyyymmdd.pcap
```

to transfer PCAP files to my PC.

**Comment by GermMuz** [comment] 2016-01-30 12:55
I've tried the file via google drive and adb, having created a new file. I've also quickly written a C# program to look at the file header. I also created a pcap file for my wired Ethernet adapter as a reference.

The magic number etc. comes out correct for the wireshark captured file but I get Hex: 56ABF750 for netguard. The major and minor numbers are also in error.

Maybe I am creating the file wrong. I have turned on logging in the settings, enabled pcap, and then done a pcap export.

**Comment by M66B** [comment] 2016-01-30 12:58
This could be a problem with byte ordering or padding.
Can you please show the first 24 bytes in hex of the file?

**Comment by GermMuz** [comment] 2016-01-31 14:34
Here are the first 24 bytes:

50 F7 AB 56 B1 DF C 0 3C 0 0 0 3C 0 0 0 45 0 0 3C 95 40 40 0

the magic number etc. are missing, and for a working pcap file caught using wireshark:

D4 C3 B2 A1 2 0 4 0 0 0 0 0 0 0 0 0 0 0 4 0 1 0 0 0

**Comment by M66B** [comment] 2016-01-31 14:36
I have received another corrupt file from somebody else, but unfortunately I don't have an explanation for this. Maybe you can try to clear the file (menu clear will also reset the PCAP file) and check if the file after that is okay. It would be useful to know what the result is of this action, so we can narrow down the search.

**Comment by M66B** [comment] 2016-01-31 14:37
Which device do you use? Which processor architecture?

**Comment by GermMuz** [comment] 2016-01-31 14:39
I've tried that. I've also added in some debug to the source and the pcap header seems only to be written if you do a clear. I would be tempted to write the header all the time, I might try that. A lot of the time setpcap is started with init = false.

I am using a nexus 5 with Android 6

**Comment by M66B** [comment] 2016-01-31 14:43
Can you please check if the last commit fixes this problem?

**Comment by GermMuz** [comment] 2016-01-31 14:56
Sorry but no. I caught a file and tried reading it using Android 'pcap reader' (from the store and it failed.

**Comment by M66B** [comment] 2016-01-31 15:09
I hope you did clear the file first.

**Comment by GermMuz** [comment] 2016-01-31 21:40
I still have an issue and so edited the code to always save out exactly known packets, i changed write_pcap_rec to do his. The header is correct now. But between the pcap file header and the first packet there are 32 bytes that are 'random' and this is the problem now. I have not yet found where they are written yet but they are the problem.

**Comment by M66B** [comment] 2016-01-31 21:43
This might be a padding/alignment problem, which might be caused by the compiler or by incorrect struct attributes.

Could you please check if my build (latest beta) has this same problem, so we can narrow down the search?

**Comment by M66B** [comment] 2016-01-31 21:51
Another thing you can do, is check the length write_pcap_rec reports against the size of the PCAP header.

**Comment by GermMuz** [comment] 2016-02-01 19:19
Well done, the latest version from a few minutes ago works :)

**Closed** 2016-02-01 19:20 UTC
Labels: question

**Comment by M66B** [comment] 2016-02-01 19:26
Nice, especially because I forgot to test the fix (which is letting the native code decide whether to write the PCAP header, also simplifying the native API).
