### ISSUE TITLE
argument to '-x' is missing

### ISSUE THREAD

**Issue by GauravCreed** [M66B/NetGuard#445] opened 2016-06-16 06:46 UTC
hi @M66B 

I just download your code and try to run but it will give error like that 

`Information:Gradle tasks [:app:assembleAllDebug]
Observed package id 'build-tools;20.0.0' in inconsistent location 'D:\Software\C-world soft\adt-bundle-windows-x86-20140702\sdk\build-tools\android-4.4W' (Expected 'D:\Software\C-world soft\adt-bundle-windows-x86-20140702\sdk\build-tools\20.0.0')
:app:compileNetguardArmeabi-v7aDebugSharedLibraryNetguardMainC
Error:error: argument to '-x' is missing (expected 1 value)
Error:error: no input files
Error:error: argument to '-x' is missing (expected 1 value)
Error:error: no input files
Error:error: argument to '-x' is missing (expected 1 value)
Error:error: no input files
Error:error: argument to '-x' is missing (expected 1 value)
Error:error: no input files
Error:error: argument to '-x' is missing (expected 1 value)
Error:error: no input files
Error:error: argument to '-x' is missing (expected 1 value)
Error:error: no input files
Error:error: argument to '-x' is missing (expected 1 value)
Error:error: no input files
Error:error: argument to '-x' is missing (expected 1 value)
Error:error: no input files
Error:error: argument to '-x' is missing (expected 1 value)
Error:error: no input files
Error:error: argument to '-x' is missing (expected 1 value)
Error:error: no input files
Error:Execution failed for task ':app:compileNetguardArmeabi-v7aDebugSharedLibraryNetguardMainC'.
> Multiple build operations failed.
      C compiler failed while compiling dns.c.
      C compiler failed while compiling icmp.c.
      C compiler failed while compiling ip.c.
      C compiler failed while compiling dhcp.c.
      C compiler failed while compiling netguard.c.
      C compiler failed while compiling pcap.c.
      C compiler failed while compiling session.c.
      C compiler failed while compiling tcp.c.
      C compiler failed while compiling udp.c.
      C compiler failed while compiling util.c.
  See the complete log at: file:///E:/All%20Workspace/Prashant%20bhai/AndroidStudio/NetGuard/NetGuard-master/app/build/tmp/compileNetguardArmeabi-v7aDebugSharedLibraryNetguardMainC/output.txt
Information:BUILD FAILED
Information:Total time: 1.542 secs
Information:21 errors
Information:0 warnings
Information:See complete output in console`

Then i just change as u say in closed Issue in mu **Build.gradle** file like 

`ndk {
            platformVersion = "15"
            moduleName = "netguard"
            toolchain = "clang"
            toolchainVersion = "3.5"
            ldLibs.add("log")
        }`

Then it will show error something like 
`Error:Unable to find toolchain: D:\Software\NDK\androidndk\toolchains\llvm-3.5\prebuilt`

can u please help me to solve this issue.

thanks.

**Comment by licaon-kter** [comment] 2016-06-16 07:36
Building natively on Windows is not really supported. See https://github.com/M66B/NetGuard#contributing

/duplicate of #429 & #386 & #384 & #287 & #258 & #238

**Comment by GauravCreed** [comment] 2016-06-16 09:17
thanks for the response quick.

As per your guidance i refer the document, if i am not wrong prebuilt versions of NetGuard is Provided by you on this [https://github.com/M66B/NetGuard/releases](url), then i also download code NetGuard 2.25 stable source code.

then the project will give build error like..

`Information:Gradle tasks [:app:assembleAllDebug]
Observed package id 'build-tools;20.0.0' in inconsistent location 'D:\Software\C-world soft\adt-bundle-windows-x86-20140702\sdk\build-tools\android-4.4W' (Expected 'D:\Software\C-world soft\adt-bundle-windows-x86-20140702\sdk\build-tools\20.0.0')
:app:compileNetguardArmeabi-v7aDebugSharedLibraryNetguardMainC UP-TO-DATE
:app:linkNetguardArmeabi-v7aDebugSharedLibrary
Error:error: unable to execute command: Couldn't execute program 'D:\Software\NDK\androidndk\toolchains\arm-linux-androideabi-4.9\prebuilt\windows-x86_64/lib/gcc/arm-linux-androideabi/4.9/../../../../arm-linux-androideabi/bin\ld.exe'Unknown error
Error:error: linker command failed with exit code 1 (use -v to see invocation)
Error:Execution failed for task ':app:linkNetguardArmeabi-v7aDebugSharedLibrary'.
> A build operation failed.
      Linker failed while linking libnetguard.so.
  See the complete log at: file:///E:/Backup/Github%20Demos/NetGuard-2.25/app/build/tmp/linkNetguardArmeabi-v7aDebugSharedLibrary/output.txt
Information:BUILD FAILED`


is there any solution for this.?

Thanks.

**Comment by M66B** [comment] 2016-06-16 11:00
If you want to build NetGuard yourself, it is assumed you know how to and can solve proverbs yourself. Of your cannot, you can use the prebuilt versions. There is no support in building, sorry.

**Closed** 2016-06-16 11:02 UTC
