### ISSUE TITLE
can't build application

### ISSUE THREAD

**Issue by archish1989** [M66B/NetGuard#287] opened 2016-02-05 09:08 UTC
i download source code form master branch and while debugging app, i am having following error.

Information:Gradle tasks [:app:assembleAllDebug]
:app:copyArmeabi-v7aDebugNetguardSharedLibraryGdbServer UP-TO-DATE
:app:createArmeabi-v7aDebugNetguardSharedLibraryGdbsetup
:app:compileArmeabi-v7aDebugNetguardSharedLibraryNetguardMainC
This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
Assertion failed!
Program: G:\AndroidNDK\android-ndk-r10e\toolchains\llvm-3.6\prebuilt\windows-x86_64\bin\clang.exe
File: /s/ndk-toolchain/src/llvm-3.6/llvm/lib/Option/OptTable.cpp, Line 285
Expression: Index >= End && "Unexpected parser error."
Error:Execution failed for task ':app:compileArmeabi-v7aDebugNetguardSharedLibraryNetguardMainC'.
> A build operation failed.
      C compiler failed while compiling netguard.c.
  See the complete log at: file:///C:/Users/arch/Downloads/NetGuard-master/NetGuard-master/app/build/tmp/compileArmeabi-v7aDebugNetguardSharedLibraryNetguardMainC/output.txt
Information:BUILD FAILED
Information:Total time: 13.838 secs
Information:1 error
Information:0 warnings
Information:See complete output in console 

and this is what in output file.

See file:///C:/Users/arch/Downloads/NetGuard-master/NetGuard-master/app/build/tmp/compileArmeabi-v7aDebugNetguardSharedLibraryNetguardMainC/output.txt for all output for compileArmeabi-v7aDebugNetguardSharedLibraryNetguardMainC.
compiling netguard.c failed.

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
Assertion failed!

Program: G:\AndroidNDK\android-ndk-r10e\toolchains\llvm-3.6\prebuilt\windows-x86_64\bin\clang.exe
File: /s/ndk-toolchain/src/llvm-3.6/llvm/lib/Option/OptTable.cpp, Line 285

Expression: Index >= End && "Unexpected parser error."

Finished compileArmeabi-v7aDebugNetguardSharedLibraryNetguardMainC, see full log file:///C:/Users/arch/Downloads/NetGuard-master/NetGuard-master/app/build/tmp/compileArmeabi-v7aDebugNetguardSharedLibraryNetguardMainC/output.txt.

please help

**Comment by M66B** [comment] 2016-02-05 09:11
Duplicate of #238 

If you want to build yourself I am expecting you can solve build errors on your own.
If you can't, then you can use the versions.

**Closed by M66B** 2016-02-05 09:11 UTC
