### ISSUE TITLE
Would it make sense to resolve hosts to block by IP as well?

### ISSUE THREAD

**Issue by RoxKilly** [M66B/NetGuard#379] opened 2016-03-20 00:19 UTC
This idea just occurred to me; I don't know whether it's any good but I wondered what you think of it.

People use a hosts file because they don't want to connect and exchange data with a domain, say `sourceforge.com`.  So the software adds `0.0.0.0 sourceforge.com` to the hosts.  Malware can typically get around this by connecting directly by IP address, say `http://216.34.181.60/evil.php`.

When a hosts file is applied, have you considered resolving the domains' true IPs and adding them to a global IP filter ruleset?  For a few thousand domains, I suspect this would take a while (15 minutes? 30?) especially since one domain can resolve to a few different IPs, so the process would need to be done in the background.  This ruleset would only be scanned _after_ a request clears the hosts block.

In the UI, this additional scan could be presented as a checkbox enabled only if the user chooses to download a hosts file.

Besides the time to resolve IPs, and the additional CPU cycles needed to implement the filters, the other downside I see is that domains often change IPs, so the ruleset would grow outdated and would need to be re-validated - maybe whenever a new hosts file is downloaded, or on a weekly schedule?

**Comment by licaon-kter** [comment] 2016-03-20 00:43
IP lists are kinda bad, you will have servers hosting multiple sites, blocking the legit ones with the bad one.

**Comment by RoxKilly** [comment] 2016-03-20 00:46
@licaon-kter  that's a wonderful point that I overlooked. That's why it's great to bounce ideas.  Thanks.

**Comment by licaon-kter** [comment] 2016-03-20 00:47
/duplicate of https://github.com/M66B/NetGuard/issues/79 maybe :)

**Comment by RoxKilly** [comment] 2016-03-20 00:56
Yes there is overlap between the two issues. Marcel also makes a great point (similar to yours) about sites using commercial proxies such as Cloudflare.  A lot of sites will go through the same proxies and share a common IP.

**Comment by M66B** [comment] 2016-03-20 06:21
Besides using the hosts file, there is already an option to filter IP addresses, which works by resolving IPs, so I don't see the need for this features.

**Closed** 2016-03-20 10:49 UTC
Labels: enhancement, wontfix
