### ISSUE TITLE
Merging speed notification with the Netguard notification (if activated)

### ISSUE THREAD

**Issue by actinium227** [M66B/NetGuard#327] opened 2016-02-18 04:06 UTC
when the speed notification is running the Netguard notification seems a bit redundant, though I am not sure what should happen when the screen transition between on / off, maybe make the speed notification persist (and just update with the screen on?)

**Comment by licaon-kter** [comment] 2016-02-18 06:19
Duplicate of https://github.com/M66B/NetGuard/issues/194

**Closed** 2016-02-18 06:46 UTC
Labels: duplicate
