### ISSUE TITLE
Share anonymized usage data to improve NetGuard

### ISSUE THREAD

**Issue by licaon-kter** [M66B/NetGuard#461] opened 2016-07-08 16:40 UTC
Did you plan out how this would play out?

Maybe a `Community recommendation: BLOCK this app` notification on app install? (modified current notification I mean)

But would that be for the PRO users only like in Xprivacy?

**Comment by M66B** [comment] 2016-07-08 16:59
First we need data, then a statistical method to properly aggregate data and then we will see further.
Keep an eye on this: https://crowd.netguard.me/

**Comment by licaon-kter** [comment] 2016-07-09 10:31
What's the *clock icon* column for?

**Comment by M66B** [comment] 2016-07-09 10:50
You can hover over the icons to see a description.

Some applications are not listed in the Play store indeed.

**Comment by licaon-kter** [comment] 2016-07-09 11:02
Oh, saw it now, thanks.

**Comment by M66B** [comment] 2016-07-10 08:06
I have added statistics to https://crowd.netguard.me/

**Comment by micressor** [comment] 2016-07-12 18:04
It is absolutly **not OK** to gather this data without an **Opt-In** of each induvidual user!
Independent of a **Pro** or **normal** user. Independent that the data is anonym.
Please stop to proceed this way!

**Comment by M66B** [comment] 2016-07-12 18:09
Everybody opts in at first start or first update with this, so you have the choice to accept this and use NetGuard for free or to not accept this and not use NetGuard for free. You can also acquire one of the pro features and disable this.

Everything about sending usage data is communicated in an open and clear way, which cannot be said of many/most other applications out there.

**Comment by micressor** [comment] 2016-07-12 18:54
I understand, but NetGuard is a firewall product and should be under control 100% by the owner.
I have pro features and I am a fan. But what I see now, is wrong!
For me it looks like an attempt to blackmail users to buy pro features.
It is an ethic thing!
Please think about.

**Comment by M66B** [comment] 2016-07-12 19:02
I think it is fair that people using the free version contribute by sharing their usage data and I think it is fair that people using one or more of the pro features have the option to disable this. I don't feel people are being blackmailed, it is just a trade. This applies to both existing and new users, so everybody is treated equally.

If you see room for improvement, please let me know.

**Comment by mva1985** [comment] 2016-07-12 19:06
NetGuard, is awesome it actually let's me know who other apps are communicating with.  Eye opening indeed.  I can even examine the communication of another app developed by the Author, BackPackTrackII.

I have pro features but have left the data sharing enabled because I trust this developer.

**Comment by M66B** [comment] 2016-07-12 19:06
Also, the goal is to improve NetGuard, which benefits everybody.

In fact I have learned already a few things, which will influence future developments.

**Comment by M66B** [comment] 2016-07-12 19:08
@mva1985 thanks for your trust and letting the usage data sharing enabled.

**Comment by micressor** [comment] 2016-07-12 19:28
I understand the need to improve NetGuard and to do this with anonymized data.
Please remove statistics with breakdown to applications. That's too much.
Room for improvement: Users should be able to configure which data to share.

I not agree, not happy about this progress.

@mva1985: I support NetGuard **and** privacy is a really important thing. It should be in unison. I am afraid that it get worse this way.

**Comment by M66B** [comment] 2016-07-12 19:48
What is wrong about the breakdown to applications?

**Comment by M66B** [comment] 2016-07-12 20:02
No privacy sensitive data (=data that can identify someone) is being shared, so I don't see what selecting data to share will add besides complexity and confusion.

This is the data being shared:
https://github.com/M66B/NetGuard/blob/master/FAQ.md#FAQ39

The idea is that people using the free version will contribute to the NetGuard project by sharing harmless data.

If you don't agree the shared data is harmless, please tell me why.

**Comment by adisib** [comment] 2016-07-12 20:19
I understand that NetGuard isn't sending any sensitive data and it is sent anonymously. But forcing data sharing for free users is contrary to what the app is about. It is an app designed to improve privacy and prevent data from being sent. If not everything can be blocked, then it seems like a pretty bad firewall.

That being said, I do not wish to disable data sharing for myself; I want to keep it enabled to help the app development. But forcing data sharing just goes against the principle of a firewall and seems like a bad idea. A good firewall app should be able to block itself.

**Comment by M66B** [comment] 2016-07-12 20:29
First of all, I like to say that I appreciate the discussion here. In fact I am surprised not more people joined the discussion yet.

@adisib: I don't see why not being able to block NetGuard with itself, which is a kind of paradox anyway, makes NetGuard a bad firewall.

**Comment by adisib** [comment] 2016-07-12 20:38
Perhaps that was taken a bit too literally. The point is, a firewall should allow control over data sent. The more data that can get through without a user's consent, the worse of a firewall it is. Forcing data sharing is allowing data to get through without a user's consent, i.e. making it a worse firewall.

I haven't purchased any features because I wanted to see how well the app worked before I donated any money to it by buying features. Really the fact that it forces data sharing for free users is the only reason I still haven't thrown any money towards it. It is an otherwise great app (except that it could use a bit of very minor organizational improvements).

**Comment by M66B** [comment] 2016-07-12 20:43
Still there is the paradox of NetGuard controlling itself. Like often, it boils down to trust.

**Comment by M66B** [comment] 2016-07-12 20:44
I like to hear about which organizational improvements can be made in another issue.

**Comment by licaon-kter** [comment] 2016-07-12 21:48
Can we get an in app button (near submit checkbox I guess) that opens the crowd page?

**Comment by micressor** [comment] 2016-07-12 22:00
As @adisib said, the point is "a firewall should allow control over data sent".

For me this issue is solved, as soon as **free** users are no longer forced to share statistic data.

And @M66B as one of your **pro** users I'd like to help NetGuard and would like to send statistic data, as soon as I have more control over which data I share.

Keep in mind, free users are not your enemies, they are just your **fans** to become **pro** users.

**Comment by licaon-kter** [comment] 2016-07-12 22:10
> The configured country (this is not the country where the device is located)

Maybe this needs some clarification in the FAQ, sounds not so harmless.

> Which internet addresses (protocol, version, host, port) will be allowed and blocked

So is NetGuard uploading my hosts file to your server then?

**Comment by M66B** [comment] 2016-07-13 04:52
> Can we get an in app button (near submit checkbox I guess) that opens the crowd page?

I am planning something better than that: a dialog to fetch settings.

**Comment by M66B** [comment] 2016-07-13 05:13
> As @adisib said, the point is "a firewall should allow control over data sent".
> 
> For me this issue is solved, as soon as free users are no longer forced to share statistic data.
> 
> And @M66B as one of your pro users I'd like to help NetGuard and would like to send statistic data, as soon as I have more control over which data I share.
> 
> Keep in mind, free users are not your enemies, they are just your fans to become pro users.

NetGuard gives you control over the data sent by other applications as good as it can, without requiring root permissions and even for free, in the next version in return for sharing anonymized usage data. More than 99% of the free version users will never acquire any pro feature and in this way they will contribute something useful to the project that benefits everybody. I think that is fair. Note that I have also put *a lot* of time into this project for free and very few people like @licaon-kter try to help me with this, on the contrary, there is a constant stream of support questions and unfair low rating, which demotivate me at times.

Letting people select the usage data to share will be a problem for statistical analysis, therefore it can only be on or off. I am open to discuss about what will be sent for everybody, however. The goal is to make shared settings available to everybody, but people are different. Some people use NetGuard to reduce data usage and other people use NetGuard to block ads. If there is enough usage data I will try to use statistical analysis to group settings by their purpose. For example settings that whitelist something are different from settings that blacklist something.

**Comment by M66B** [comment] 2016-07-13 05:23
> Maybe this needs some clarification in the FAQ, sounds not so harmless.

The country people selected when initializing Android is part of the usage data, because people of different countries are using NetGuard for different reasons. Some countries have expensive mobile internet and/or tight data bundles. These people tend to use NetGuard mainly to reduce data use.

Note that the country people selected when initializing Android might not be the same country where they currently are. If they are travelling or even if they are living abroad, they would likely still have selected their home country to have Android presents itself in their mother language.

> So is NetGuard uploading my hosts file to your server then?

No, it isn't and it wouldn't be useful as well, since hosts files are readily available on the internet. The addresses you explicitly block or allow per application are being shared to be able to make the same exception when somebody want to retrieve settings for the same application.

**Comment by mgafner** [comment] 2016-07-13 06:25
In my point of view it would be ethical correct to share data in an opt-in manner. Even in the free version.

**Comment by M66B** [comment] 2016-07-13 06:28
In my point of view it would be ethical correct if people contribute something to the project. Even in the free version. The point is there are different perspectives which needs to be balanced.

**Comment by M66B** [comment] 2016-07-13 06:31
Also, people opt-in by explicitly agreeing to this. If people don't like to share usage data, they can choose to use another firewall application.

**Comment by micressor** [comment] 2016-07-13 07:13
>Also, people opt-in by explicitly agreeing to this. If people don't like to share usage data, they can choose to use another firewall application.

It feels to me very egoistic.
I understand your point, you'd like to have more financial support for this project, but I never saw, that you [wrote it down](https://github.com/M66B/NetGuard/blob/master/FAQ.md#FAQ39).
But why you don't ask your users via NetGuard App/Crowdfunding for help and support?

**Comment by M66B** [comment] 2016-07-13 07:38
The shared usage data might be made available in the form of crowd sourced settings. Accessing the crowd sourced settings might also be available after a purchase only, but does this make me egoistic? So far I have been working hundreds of hours for free on NetGuard, which is also 100% open source. Doesn't this say the opposite of egoistic? Moreover, me being egoistic or not is not a real argument of concern regarding sharing usage data.

There are currently [over 2000 commits](https://github.com/M66B/NetGuard/). I think it is conservative to say I spent at least 15 minutes on average each commit, which would mean I have spent at least 500 hours so far.

So far, usage data is only being shared by beta versions of NetGuard to iron out any problems and concerns, so the volume of the usage data is still low. Letting the usage data share by the stable version of NetGuard will likely increase the volume of data significantly, which might require significant server capacity. Server capacity needs to be paid for, so making the crowd sourced settings paid might even be a necessity.

I have been asking for help and support frequently and not only for this project. In practice this just doesn't work. Note that I have been publishing open source application for years already.

**Comment by micressor** [comment] 2016-07-13 07:58
Yes I noticed, that you do a very good opensource job! Thanks a lot for this!

Do I unerstand you right:
* Only NetGuard beta versions send statistic data to you?
* Stable versions do not send statistic data?

**Comment by M66B** [comment] 2016-07-13 08:06
For now only beta version share usage data, but this will change after everything has been found stable. For now everything looks good, so this could be soon.

**Comment by M66B** [comment] 2016-07-13 08:13
I have changed [the listed applications](https://crowd.netguard.me/) to applications listed in the Play store only to take away any concern about private application being listed. Before private applications were filtered as well, because only application installed on several devices were being listed, but the new method is safer and has as advantage that all Play store links will work now. However, the disadvantage is that applications not listed in the Play, for example side loaded applications or applications installed through other market applications like F-Droid, are not being listed anymore.

**Comment by M66B** [comment] 2016-07-13 09:09
Another way to look at the effort put into NetGuard: https://www.openhub.net/p/netguard/estimated_cost

**Comment by micressor** [comment] 2016-07-13 09:15
> @M66B  wrote: Everything about sending usage data is communicated in an open and clear way, which cannot be said of many/most other applications out there.

To be transparent in your communication, please write down ([FAQ](https://github.com/M66B/NetGuard/blob/master/FAQ.md#FAQ39)), why free users can disable sharing of statistics **only in a purchased version.** To improove NetGuard is obviously (discussion from [#461](https://github.com/M66B/NetGuard/issues/461#issuecomment-232129273)) not the only cause.

**Comment by M66B** [comment] 2016-07-13 09:27
> To be transparent in your communication, please write down (FAQ), why free users can disable sharing of statistics only in a purchased version. To improve NetGuard is obviously (discussion from #461) not the only cause.

I don't see what needs to be added to the FAQ regarding disabling sharing usage data, but maybe I am missing something? In my idea the sole purpose of sharing usage data is improving NetGuard.

> Is it not a much better business model to limit count of Apps that can be blocked/allowed in a free version?

First of all there is no business model because NetGuard is not a business. Even if limiting the number of applications which can be managed in the free version was a good idea, it is not allowed by the Google [Play Developer Distribution Agreement](https://play.google.com/about/developer-distribution-agreement.html) section 3.5 to change free features into paid features.

**Comment by micressor** [comment] 2016-07-13 10:40
>I don't see what needs to be added to the FAQ regarding disabling sharing usage data, but maybe I am missing something? In my idea the sole purpose of sharing usage data is improving NetGuard.

You wrote it already what is missing in the [FAQ](https://github.com/M66B/NetGuard/blob/master/FAQ.md#FAQ39):
>  NetGuard gives you control over the data sent by other applications as good as it can, without requiring root permissions and even for free, in the next version in return for sharing anonymized usage data. **More than 99% of the free version users will never acquire any pro feature and in this way they will contribute something useful to the project that benefits everybody.** I think that is fair.

And may be you like more support from your NetGuard users in a **code line** or **money** based way?

> First of all there is no business model because NetGuard is not a business.

When it is not a business, why are there payable pro features?
What I miss is (for example) a call for monthly donations in the netguard app and on the github page.

> I have been asking for help and support frequently and not only for this project. In practice this just doesn't work.

To enforce users to pay, to get their privacy back is not a fairtrade.
But I understood why you did it.
The kind you do this, is a little bit unhappy.

> Note that I have put a lot of time and effort into this project for free and very few people like @licaon-kter try to help me with this, on the contrary, there is a constant stream of support questions and unfair low rating, which demotivate me at times.

Yes I see that it is a lot of work, thank you so much! Also thanks to you @licaon-kter .

Another try to improve: What if you enforce statistic sharing for the **free version** not before 3 months after first use?  So if a user uses NetGuard for a longer time, it seems that he/she like the NetGuard App. So a donation or buy a pro-feature would be the next fair step.

**Comment by M66B** [comment] 2016-07-13 11:09
I don't think that adding the statistic that more than 99% of the free version users will never acquire any pro features adds anything significant to the main purpose of improving NetGuard.

The little money I get from Play store purchases and donations is meant as a kind of positive feedback for the things I do, not to earn money. Just few people give feedback in other ways and then often only in the form of questions or problems. In my view feedback includes contributing code, documentation and translations and useful discussions like the one that is taking place here.

You keep saying/implying that sharing usage data is a violation of privacy. I have made sure that this is not the case. If you think otherwise, then please indicate how, so it can be addressed.

Sharing usage data after three months would not contribute very much to the purpose of improving NetGuard.

**Comment by licaon-kter** [comment] 2016-07-13 11:20
@micressor 
> Yes I see that it is a lot of work, thank you so much! Also thanks to you @licaon-kter .

Nonono, see #291 or #420, I image @M66B waking up every morning and raging seeing yet another logcat from my devices. :) They're fixed now but the constant posting must have been maddening.



@M66B 
>  The addresses you explicitly block or allow per application are being shared to be able to make the same exception when somebody want to retrieve settings for the same application.

Umm free users can't block hosts (except from a hosts file) hence my query ;)

**Comment by M66B** [comment] 2016-07-13 11:25
> Umm free users can't block hosts (except from a hosts file) hence my query ;)
But people having this pro feature can, so data shared about this can be useful to other pro feature users.

**Comment by micressor** [comment] 2016-07-13 12:55
> I don't think that adding the statistic that more than 99% of the free version users will never acquire any pro features adds anything significant to the main purpose of improving NetGuard.

It would explain your decison **to enforce** statistic share for **free version** users.

> In my view feedback includes contributing code, documentation and translations and useful discussions like the one that is taking place here.

In this project for example, I am only able to support with money (and discussions) :)
So let NetGuard users know, how much money in a monthly (Paypal, Bank) subscription would help and keep up your motivation to bring forward this greate product.

> You keep saying/implying that sharing usage data is a violation of privacy.

1. **Yes, if** there is no possibility to Self-Opt-Out for all users
2. Default Opt-In with possibility to Self-Opt-Out would be acceptable.
3. @adisib said: "The point is, a firewall should allow control over data sent."
4. The anonymisation part at https://crowd.netguard.me/ looks o.k. to me.

**Comment by M66B** [comment] 2016-07-13 13:11
> It would explain your decison to enforce statistic share for free version users.

I will add this to the FAQ if people are going to ask about this, also to save myself time to answer questions about this.

> So let NetGuard users know, how much money in a monthly (Paypal, Bank) subscription would help and keep up your motivation to bring forward this greate product.

It is not about the absolute amount of money I get.

>The anonymisation part at https://crowd.netguard.me/ looks o.k. to me.

So, why needs there be an option to opt out?

**Comment by M66B** [comment] 2016-07-13 13:38
I like to be clear about that people opt-in after a transparent message about what is going to happen. Opting-out basically means not using NetGuard, with an exception for pro feature users.

I have already answered to the statement that a firewall should allow control over data sent.

**Comment by micressor** [comment] 2016-07-13 16:49
> So, why needs there be an option to opt out?

To respect privacy of your NetGuard users. It is not a anonymized or not anonymized thing - it's a respect thing. In Firefox for example it is optional to send usage data.

> I think it is fair that people using the free version contribute by sharing their usage data and I think it is fair that people using one or more of the pro features have the option to disable this.

Yes it is fair and it is **not a fairtrade to enforce it.**

> No privacy sensitive data (=data that can identify someone) is being shared, so I don't see what selecting data to share will add besides complexity and confusion.

It seems to me, that the expression **sensitive data** has different characteristic and different interpretations.

> I have already answered to the statement that a firewall should allow control over data sent.
> Still there is the paradox of NetGuard controlling itself. Like often, it boils down to trust.

I don't like it, if I have only 99% control about how data flow trough NetGuard.
That violates the base principles of a firewall.

> NetGuard gives you control over the data sent by other applications as good as it can, without requiring root permissions and even for free, in the next version in return for sharing anonymized usage data.

No, it was 100% some versions ago.

> I like to be clear about that people opt-in after a transparent message about what is going to  happen. Opting-out basically means not using NetGuard, with an exception for pro feature users.

It is your decision, but I definitely not agree with this approach.

> The little money I get from Play store purchases and donations is meant as a kind of positive feedback for the things I do, not to earn money. 

If it is not the money, why do you enforce it?
What do you want really?

**Comment by M66B** [comment] 2016-07-13 17:12
Most of your remarks are based on the idea that privacy sensitive usage data is being shared. This is not the case, but if you think otherwise, please let me know which data is privacy sensitive in your opinion, so we discuss about it.

The usage data is shared to be able to improve NetGuard, which might include letting people import settings based on the settings of other people. For this to work properly there needs to be an unbiased usage data set, hence why I don't want to make sharing usage data optional.

> What do you want really?

Be the richest man in the world, control the world, control your mind, if that is what you are searching for, then you are not going to find it. I live a modest life and believe that most unhappiness is being caused by our own desires.

I understand that you are suspicious, because a lot of bad things happen, but not here.

**Comment by M66B** [comment] 2016-07-13 17:22
I am considering to remove the option to let pro feature users disable usage data sharing, to take away the idea that for not sharing usage data needs to be paid. It would also make the usage data set less biased.

**Comment by micressor** [comment] 2016-07-13 17:33
Independent from **free** or **pro** users, it violates the base principles of a firewall. I never saw a firewall that enforce such a behavior. Hope other people will give feedback here too.

**Comment by web-web** [comment] 2016-07-13 18:41
I'll downgrade NetGuard to version 2.28 to avoid completely data sharing "feature" !

**Comment by M66B** [comment] 2016-07-13 18:44
@web-web okay, but why?

**Comment by web-web** [comment] 2016-07-13 18:46
I don't agree to share any "user usage data" !!
I'm using your software to stop sending-out data, not to send-out ANY data!

**Comment by M66B** [comment] 2016-07-13 18:47
I have just added an option to disable sharing usage data per application. I hope that this addresses the concerns expressed in this issue. IMHO this is a good compromis between striving towards a unbiased usage data set and allowing people to (selectively) disable sharing usage data.

**Comment by M66B** [comment] 2016-07-13 18:47
@web-web but why?

**Comment by web-web** [comment] 2016-07-13 18:50
Because I don't like to have any software installed that have its own control over my device (OR device's data), even if that is only any statistical data!

**Comment by mgafner** [comment] 2016-07-13 18:54
As I understood, the sharing of data is used to prepare preconfigured filtersets for users who don't want to configure everything by themself, right? Let us name this a feature.

Now, users who want to use that feature, they have to activate the sharing of usage data. For the other users (free and pro), they can opt-in if they want to contribute. Could that be a compromise?

**Comment by M66B** [comment] 2016-07-13 18:57
@mgafner that is an interesting idea, but there are some practical problems:

* Usage data sharing needs to be kept enabled to prevent cheating
* We have to find a solution to pay for the server costs

**Comment by web-web** [comment] 2016-07-13 19:02
any software I install will have some control over my device, but that don't mean therefore any control!
When the hidden control over my device (outside my needs of that software) crossing the subjective limit, I'll have the rights to decide to completely remove it !

**Comment by mgafner** [comment] 2016-07-13 19:07
> Usage data sharing needs to be kept enabled to prevent cheating

sorry, i don't understand what you mean with that. What cheating?

<br>

> We have to find a solution to pay for the server costs

why not to make preconfigured filtersets a pro-feature?

**Comment by M66B** [comment] 2016-07-13 19:09
> sorry, i don't understand what you mean with that. What cheating?

Enable usage data sharing, fetch settings, disable usage data sharing

> why not to make preconfigured filtersets a pro-feature?

That would be an option to pay for the server costs, bu

**Comment by M66B** [comment] 2016-07-13 19:09
n

**Comment by mgafner** [comment] 2016-07-13 19:16
> Enable usage data sharing, fetch settings, disable usage data sharing

I see... ok, but you can manage this. You just don't allow to disable data sharing for a couple of days or weeks. Just an idea... which i don't like by myself. To enforce things like this in a pro feature is probably not very nice. But do you think, many users are going to cheat? Is it needed to enforce these things?

**Comment by M66B** [comment] 2016-07-13 19:20
I would like this not to be necessary, but I have learned from other projects it is unfortunately necessary.

**Comment by licaon-kter** [comment] 2016-07-14 00:51
You're betting on lazyness? Free users won't bother to disable it per app and the state is not exported with config backup. :)

**Comment by M66B** [comment] 2016-07-14 03:39
Not exporting is a bug which will be fixed.

**Comment by mgafner** [comment] 2016-07-14 05:25
> That would be an option to pay for the server costs, but then only people with this pro feature would share usage data, which would have a significant impact on the quality of the usage data.

yes, when sharing data is only activated in the pro feature. But my idea as written above is to allow the other users (free and pro) to opt-in if they want to contribute.

**Comment by M66B** [comment] 2016-07-14 05:36
Since [beta version 2.35](https://github.com/M66B/NetGuard/releases) it is like this:

* People accept opt in at first run (or first update)
* People can disable sharing usage data per application with a setting
* There is no difference between free and pro feature users anymore.

This is the best compromise I could come up with between the ability to disable sharing usage data and to have an unbiased data set.

**Comment by micressor** [comment] 2016-07-15 12:31
This is a compromise which I can live. Now I feel the 100% control which data is sent. Thanks.

**Comment by M66B** [comment] 2016-07-15 12:40
Good, nevertheless I hope most of you will be able to set aside the unfounded feeling something bad is happening and will keep sharing usage data enabled to help build a [usable data set](https://crowd.netguard.me) which can later be used by others to quickly and correctly configure NetGuard.

**Comment by licaon-kter** [comment] 2016-07-15 17:48
So users can opt-out of the "per-app data" sharing, but what happens with the other data:
* The SHA256 hashed Android ID (needed to prevent multiple records of the same setting)
* The device name
* The Android version
* The country configured when initializing Android *
* Whether Wi-Fi and mobile connections will be blocked or allowed and which conditions apply (when screen on, roaming, notify on access, addresses, etc)

**Comment by M66B** [comment] 2016-07-15 17:53
Usage data is always being sent per application, so turning sharing usage data off for an application turns sending this information off as well.

**Comment by licaon-kter** [comment] 2016-07-15 18:27
That's common data (for all apps), my question was rather: _"what happens with that data if all apps are opt-out?"_

**Comment by M66B** [comment] 2016-07-15 18:29
Nothing will happen at all. Maybe I didn't explain it clearly: data is shared per application only, so this data is part of the data that is sent along with application data.

**Comment by S2-** [comment] 2016-07-17 12:58
All right. I feel betrayed and spoofed by you. I payed for the app and now you send all my personal data to your servers by default and without me opting in. And the data already left my phone and you have it now. Without asking me. And if I want to turn it off, I have to scroll though 300 apps and turn it off one by one, so you clearly made it impossible for me to do it.
Thanks. That sucks and I hope it turns around you sometime Marcel.
There are many other firewall apps that do the same and with a better user interface than yours. I payed (donated...) for your app because it is open source and I trusted you. Not for the pro features, because getting the code for that is really super easy.
Well done Marcel. I will never trust your software again. Who knows what you may hide in it in the future.


```
import java.io.UnsupportedEncodingException;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;


public class Md5 {

	public static void main(String[] args) throws NoSuchAlgorithmException, UnsupportedEncodingException {
		String text = "CB5A282UB0";
		String salt = "NetGuard";
		byte[] bytes = MessageDigest.getInstance("MD5").digest((text + salt).getBytes("UTF-8"));
		StringBuilder sb = new StringBuilder();
		for (byte b : bytes) {
			sb.append(String.format("%02X", b));
		}
		System.out.println(sb.toString());
	}
}
```

**Comment by M66B** [comment] 2016-07-17 13:08
@S2- I betrayed nobody. This change was clearly noted in the changelog, even with a reference to [a FAQ](https://github.com/M66B/NetGuard/blob/master/FAQ.md#FAQ39) that describes all details, and you opted in after updating to the first version that is sharing usage data by selecting '_I agree_' (or 'OK' in one of the first beta version).

Also, nothing bad is happening. The usage data is properly anonymized before sending and will only be used to improve NetGuard. The goal is to offer new features, so people using NetGuard will benefit from it.

The code you are listing is different from what NetGuard uses, but maybe I am missing the intention of it. There are no hard coded strings in NetGuard.
https://github.com/M66B/NetGuard/blob/master/app/src/main/java/eu/faircode/netguard/ServiceJob.java#L74
https://github.com/M66B/NetGuard/blob/master/app/src/main/java/eu/faircode/netguard/Util.java#L110

**Comment by S2-** [comment] 2016-07-17 13:14
I opted in when I had ONE button that I could switch to opt out again. You removed that, and made it 300 buttons to press. If that is not a shady thing to do nothing else is. So, how do I opt out now? You made it clearly impossible for me to. Thanks Marcel. Say "I betrayed nobody"

**Comment by mva1985** [comment] 2016-07-17 13:15
I will have to say that bit of code disturbed me.  But your explanation makes sense.  Now I'm curious where that code came from and why post it if NetGuard doesn't contain it?

**Comment by S2-** [comment] 2016-07-17 13:17
@mva1985 it came from netguard sorce repository of course.

**Comment by mva1985** [comment] 2016-07-17 13:21
I followed Marcel's links and I'm not seeing it...  Do you mind providing a link to the code you referenced?

**Comment by licaon-kter** [comment] 2016-07-17 13:27
@S2- Yes there is a MD5 hashing function in the code but is used to hash the PRO features activation code here in [ActivityPro.java#L104](https://github.com/M66B/NetGuard/blob/a9e14fdbed05b23bb6a4b46f13850b7300f0f58b/app/src/main/java/eu/faircode/netguard/ActivityPro.java#L104)

@mva1985 The main function is here in [Util.java#L526](https://github.com/M66B/NetGuard/blob/857ba8890b0eab5bf6ae70466cfba2cec19f95e3/app/src/main/java/eu/faircode/netguard/Util.java#L526 but just above you have the SHA256 in [Util.java#L110](https://github.com/M66B/NetGuard/blob/857ba8890b0eab5bf6ae70466cfba2cec19f95e3/app/src/main/java/eu/faircode/netguard/Util.java#L110) which is actually used for the shared data.

Yeah, it's hard to yell conspiracy when you have Git.

**Comment by M66B** [comment] 2016-07-17 13:32
> I opted in when I had ONE button that I could switch to opt out again. You removed that, and made it 300 buttons to press. If that is not a shady thing to do nothing else is. So, how do I opt out now? You made it clearly impossible for me to. Thanks Marcel. Say "I betrayed nobody" again, without adding a button for opting out: someone besides yourself may believe you maybe.

Yes, correct, see the discussion above. Note that beta versions are test versions where things can be wrong and can change. If you don't want this, please stick to the stable versions. I am not the person betraying people and I am sorry if you feel it this way.

>  it came from netguard source repository of course.

This is not true. Not in any of the NetGuard beta versions an MD5 hash has been used to hash the Android ID (which is in itself already a random number).

**Comment by S2-** [comment] 2016-07-17 13:42
On 17/07/2016 15:32, Marcel Bokhorst wrote:
>     I opted in when I had ONE button that I could switch to opt out
>     again. You removed that, and made it 300 buttons to press. If that
>     is not a shady thing to do nothing else is. So, how do I opt out
>     now? You made it clearly impossible for me to. Thanks Marcel. Say "I
>     betrayed nobody" again, without adding a button for opting out:
>     someone besides yourself may believe you maybe.
> 
> Yes, correct, see the discussion above.

So You agree it is a shaddy thing to do.

> Note that beta versions are test
> versions where things can be wrong and can change.

So it is a bug of the beta version? I really hope so.

> If you don't want
> this, please stick to the stable versions. I am not the person betraying
> people and I am sorry if you feel it this way.

I don't think you are sorry. See discussion above. You clearly did it on
purpose to force people to opt in. But I don't care about "crowdsourcing
settings" or all the other stuff. I handcraft my settings, and I like it
that way. Please respect my way of seeing it. Don't force me to your way
of doing things.

>     it came from netguard source repository of course.
> 
> This is not true.

So you are saying I am a lair now? Where should that code come from
then? It generates a valid pro features activation code. If that code is
not from here, and as you say "There are no hard coded strings in
NetGuard" that code does not work and does not generate a valid
activation code.

> Not in any of the NetGuard beta versions an MD5 hash
> has been used to hash the Android ID (which is in itself already a
> random number).

So what is your point then?

**Comment by M66B** [comment] 2016-07-17 13:54
No, I don't agree it is a shaddy thing to do. Beta versions are test versions where things can change and this has been changed after discussion and new insights.

Yes, I did it on purpose with IMHO a good reason, but that doesn't mean I don't care if people feel bad about what I did.

I do respect your way of seeing it, but regarding NetGuard I have to make the choices, because I am the developer. I hope you have respect for that too, even if it doesn't suite you. I am always open to discussion, especially if there are good arguments.

I am not saying you are a lier, just that you were looking at the wrong code. Note that I referenced the correct code and you still said '_it came from netguard source repository of course_', which I found worth the deny to prevent confusion.

**Comment by M66B** [comment] 2016-07-17 14:01
A general remark: I get that privacy aware people are critical, which I have nothing against, on the contrary, but please don't be overly critical and don't treat NetGuard as one of the common privacy violating applications we all know, it isn't.

**Comment by S2-** [comment] 2016-07-17 14:10
On 17/07/2016 15:54, Marcel Bokhorst wrote:
> No, I don't agree it is a shaddy thing to do. Beta versions are test
> versions where things can change and this has been changed after
> discussion and new insights.

So forcing people to opt in and making it impossible to opt out, even in
a beta, is not a shaddy thing to do for you. I think that if you really
think that your ethics are really wrong, and I feel sorry I "donated"
for your app.

> I do respect your way of seeing it, but regarding NetGuard I have to
> make the choices, because I am the developer. I hope you have respect
> for that too, even if it doesn't suite you. I am always open to
> discussion, especially if there are good arguments.

If your decisions go in the direction of sending data stored on peoples
phones to your servers without giving them a way of opting out, we have
clearly different views on how software should be done or about ethics.
But it's ok, I just didn't think you saw it this way, and "bought" this
app while having a wrong impression about you. It's my fault. Sorry
about that. Will not make same mistake again.

> I am not saying you are a lier, just that you were looking at the wrong
> code. Note that I referenced the correct code and you still said '/it
> came from netguard source repository of course/', which I found worth
> the deny to prevent confusion.

That code is not the wrong code. I pasted it to make it clear that I
"bought" the app because I believed we shared the same view on personal
data and open source, and not because I needed the code.

**Comment by licaon-kter** [comment] 2016-07-17 14:44
And the thing is that version 2.29 has no sharing and does not miss (any) features/bugfixes anyway, no need to upgrade if you don't feel it's ok.

**Comment by M66B** [comment] 2016-07-17 14:54
> So forcing people to opt in and making it impossible to opt out, even in
> a beta, is not a shaddy thing to do for you. I think that if you really
> think that your ethics are really wrong, and I feel sorry I "donated"
> for your app.

From the beginning there was a clear message on first run / update that usage data would be shared with a choice to agree/disagree, so nobody was forced to opt in. And yes, the option to disable sharing usage data was removed during the beta tests, but beta versions are test versions where things can change, is that so hard to accept? It was not a trick, just a change of mind, which was discussed above.

> That code is not the wrong code. I pasted it to make it clear that I
> "bought" the app because I believed we shared the same view on personal
> data and open source, and not because I needed the activation code.

You didn't explain this when listing the code.

And still: nothing wrong is happening. The source code is open, so if there is something wrong, please let me know and I will look into it.

**Comment by M66B** [comment] 2016-07-17 14:55
> And the thing is that version 2.29 has no sharing and does not miss (any) features/bugfixes anyway, no need to upgrade if you don't feel it's ok.

Due to limited resources only the latest version will be supported.

**Comment by M66B** [comment] 2016-07-17 15:18
Looking into the shared usage data, it appears that GitHub version users do not contribute significantly to the usage data set. Given all the complaints, I will change the behavior of NetGuard when its was installed from GitHub so that anyone wishing this can block NetGuard with itself to send usage data. Would this be acceptable?

BTW, the source code for the Play store version and the GitHub version is exactly the same, but NetGuard behaves differently when it was not installed from the Play store.

**Comment by licaon-kter** [comment] 2016-07-17 15:20
That's a given, of course.

**Comment by M66B** [comment] 2016-07-17 15:31
It appears that you can already block NetGuard with itself in the latest stable version. I had removed the code to make an exception for NetGuard itself while refactoring for the option to disable sharing usage data per application.

**Comment by S2-** [comment] 2016-07-17 15:59
So just to make it clear: the code I posted IS from NetGuard, and it is the code that generates the activation code.

The correct thing to do about sharing, **since you ask**, is obviously to let people choose. If they want to share, they share, if they want not, they do not. And that does not mean to make the opt in a one time "i agree" tap, and the opt out a 300 times "i disagree" tap.
If that means there is much less data to gather so be it. I think that crowdfunded settings are useless anyway, sending data to google may be acceptable to some, and not ok for others, so having defaults does not make much sense imho.

But, really, I think you know all that already.

**Comment by M66B** [comment] 2016-07-17 16:01
@S2- did you read this comment? https://github.com/M66B/NetGuard/issues/461#issuecomment-233187041

**Comment by S2-** [comment] 2016-07-17 16:03
@M66B I did, the second part of my answer addressed that.

**Comment by M66B** [comment] 2016-07-17 16:04
@S2- so the proposal is acceptable to you?

**Comment by S2-** [comment] 2016-07-17 16:06
@M66B IMHO the correct thing to do about sharing, is obviously to let people choose. If they want to share, they share, if they want not, they do not.

**Comment by M66B** [comment] 2016-07-17 16:08
@S2- is blocking NetGuard with itself an acceptable choice?

**Comment by S2-** [comment] 2016-07-17 16:11
@M66B I would like to trust NetGuard. I trust it with my data, and I trust it not to leak data. Personally I block apps with NetGuard that I don't trust.
Blocking it with itself disables at least one useful feature: hosts file download.

**Comment by M66B** [comment] 2016-07-17 16:14
Yes, true, you would block downloading the default provided hosts file, but you can easily configure another download location, for example the hosts file on which the default hosts file is based: 
https://github.com/M66B/NetGuard/blob/master/ADBLOCKING.md

So, this seems just a minor inconvenience to me, agreed?

**Comment by licaon-kter** [comment] 2016-07-17 16:53
I did mention on XDA there are 4 (more) ways to opt out already, blocking NetGuard was one (@M66B you really forgot you've removed this limitation? It was only in one beta iirc), then it's the hosts file (add crowd site), or if you have bought Pro you can block crowd domain for NetGuard (you can still download hosts file), or you can list all apps and create a settings XML with opt-out for all (**sed** is your friend), hey even edit source and remove submission crowd address and recompile/resign.

These are 2 trivial, 1 Pro, 2 advanced ways, but only if you've used the app and understood it's power/limitations.

And that's the thing, most users coud do this if they care, others like those installing from Google Play store, do not, it's sad but true.

**Comment by M66B** [comment] 2016-07-17 16:58
> you really forgot you've removed this limitation?

Yes, I really forgot to restore it after the refactoring I did for adding the opt-out per application. Maybe it is a surprise if I say I do many other things as well ...

> you can still download hosts file

The hosts file is on the same domain, so this will not work.

**Closed** 2016-07-18 14:10 UTC
Labels: enhancement
