### ISSUE TITLE
Can't build, problem with C compiler or am I missing something

### ISSUE THREAD

**Issue by pforpho** [M66B/NetGuard#386] opened 2016-03-22 23:55 UTC
Here's the output.txt

>  compiling dhcp.c failed.
> clang.exe: error: argument to '-x' is missing (expected 1 value)
> clang.exe: error: no input files
> 
> compiling ip.c failed.
> clang.exe: error: argument to '-x' is missing (expected 1 value)
> clang.exe: error: no input files
> 
> compiling icmp.c failed.
> clang.exe: error: argument to '-x' is missing (expected 1 value)
> clang.exe: error: no input files
> 
> compiling dns.c failed.
> clang.exe: error: argument to '-x' is missing (expected 1 value)
> clang.exe: error: no input files
> 
> compiling netguard.c failed.
> clang.exe: error: argument to '-x' is missing (expected 1 value)
> clang.exe: error: no input files
> 
> compiling session.c failed.
> clang.exe: error: argument to '-x' is missing (expected 1 value)
> clang.exe: error: no input files
> 
> compiling pcap.c failed.
> clang.exe: error: argument to '-x' is missing (expected 1 value)
> clang.exe: error: no input files
> 
> compiling tcp.c failed.
> clang.exe: error: argument to '-x' is missing (expected 1 value)
> clang.exe: error: no input files
> 
> compiling udp.c failed.
> clang.exe: error: argument to '-x' is missing (expected 1 value)
> clang.exe: error: no input files
> 
> compiling util.c failed.
> clang.exe: error: argument to '-x' is missing (expected 1 value)
> clang.exe: error: no input files
> 

I don't know if it's a problem with the C compiler, or I'm missing something.

Thanks!

**Comment by licaon-kter** [comment] 2016-03-23 00:00
Works on Linux.
Try [VirtualBox](http://virtualbox.org) + [Lubuntu](http://lubuntu.net) + [this](https://paolorotolo.github.io/android-studio/) :+1: 

/close as duplicate of https://github.com/M66B/NetGuard/issues/384 & #287 & #258 & #238

**Closed** 2016-03-23 06:16 UTC
Labels: question
