### ISSUE TITLE
Make filter function clearer

### ISSUE THREAD

**Issue by licaon-kter** [M66B/NetGuard#219] opened 2016-01-05 18:51 UTC

**Comment by M66B** [comment] 2016-01-05 21:44
Did you either check showing user or system applications?

**Comment by M66B** [comment] 2016-01-05 21:59
Fixed by https://github.com/M66B/NetGuard/commit/8a33b7d6bb07a7416fbeb0705ae6105161dd78bb

**Comment by licaon-kter** [comment] 2016-01-05 22:00
Maybe it needs more filters then?

Having **both** `system` and `disabled` will show BOTH *active* apps AND *disabled* apps, how do I see **only** the *disabled* apps?

Having **both** `user` and `no-internet` will show BOTH *with internet* apps AND *no-internet* apps, how do I see **only** the *no-internet* apps?

Not sure if closable yet, I'll rebuild now to test.

**Comment by licaon-kter** [comment] 2016-01-05 22:14
Nope, NetGuard-v0.68-2016010502 does not fix this issue.

**Comment by M66B** [comment] 2016-01-05 22:28
The filters on disabled applications and on application without internet are not meant to show only disabled application or applications without internet.

I cannot reproduce the empty list.

Toggle manage system applications once. If this doesn't help, please describe in detail what you have enabled and disabled.

**Comment by licaon-kter** [comment] 2016-01-05 22:46
Steps:
* Uninstall NetGuard.
* Install NetGuard
* enable `manage system`
* uncheck filter `user`
* uncheck filter `system`

What actually happens:
* empty list

But, if `manage system` is disabled in Settings then:
* checking only `disabled` shows `user` apps (well technically you can't disable user apps, right? they're uninstalled)
* checking only `no-internet` shows `user` apps *with* **and** *without* internet permission.

Regarding `manage system`:
* So, when `manage system` is enabled *but* `system` is not checked you should disable the `disabled` check box.
* So, when `manage system` is disabled then the `disabled` checkbox should be removed or disable.

**Comment by M66B** [comment] 2016-01-06 07:22
The empty list of to be expected with the settings as described, this is no bug.

User applications can be disabled (although this requires root).

Checking show without internet shows applications with and without internet. This is the expected behavior.

So, I see no problems.

All settings are meant to filter things away, not to display extra things.

**Comment by M66B** [comment] 2016-01-06 07:44
I recognize that you find the filters confusing and I will think about making it more clear.
Suggestions are welcome.

**Comment by licaon-kter** [comment] 2016-01-06 08:46
*All settings are meant to filter things away, not to display extra things.*

Umm, ok, right now I can't filter `user apps with internet` away.

Filters re-make:
* user w/ internet
* user w/o internet
* system w/ internet
* system w/o internet
* system disabled

**Comment by M66B** [comment] 2016-01-06 08:50
I don't see the need for filtering user/system apps with internet give the function of NetGuard.
IMO you want to see those always.

The 'no internet' filter is meant to filter applications without internet permission away.

**Closed** 2016-01-20 09:48 UTC
Labels: question
